### ISSUE TITLE
Does pos support scala 2.13.0?

### ISSUE THREAD

**Issue by Shoutmon** [JohnReedLOL/pos#19]
My scala version is 2.13.0, but I can't seem to use the pos 2.2.0 package. Does pos support scala 2.13.0, or it will be supported in the future? Thx.

My build.sbt is as follows.

```
name := "demo"

version := "0.1"

scalaVersion := "2.13.0"

resolvers += Resolver.bintrayRepo("johnreed2","maven")

libraryDependencies ++= Seq(
  "com.github.johnreedlol" %% "pos" % "2.2.0"
)
```

**Comment by JohnReedLOL** [comment]
Just published scalaVersion := "2.13.1". It should now work with both scalaVersion 2.13.0 and 2.13.1 .

To test it out I created an sbt project with the following build.sbt file:

```
name := "postest"

version := "0.1"

scalaVersion := "2.13.1"

resolvers += Resolver.bintrayRepo("johnreed2","maven")

libraryDependencies ++= Seq(
  "com.github.johnreedlol" %% "pos" % "2.2.0"
)
```

The following Main:

```
package pkg

import com.github.johnreedlol._

object Main {
  def main(args: Array[String]): Unit = {
    out("Hello World!")
  }
}
```

Output:

```
[info] running pkg.Main 
Hello World! - pkg.Main.main(Main.scala:7)
```

**Comment by JohnReedLOL** [comment]
@Shoutmon Does it work for you?

**Comment by Shoutmon** [comment]
@JohnReedLOL yes, it works perfectly. thx~
